### ISSUE TITLE
关于keras training的出现：TypeError: __int__ returned non-int (type NoneType)

### ISSUE THREAD

**Issue by houjin0803** [bojone/CLUE-bert4keras#2]
请问下苏神，我在运行cmrc2018代码的时候keras训练出现TypeError: __int__ returned non-int (type NoneType)，错误代码在keras/backend.py的4203行：logits = array_ops.reshape(output, [-1, int(output_shape[-1])])。我的keras版本是2.3.1，bert4keras版本是0.10.8，tensorflow-gpu是1.14.0，想问下苏神这个错误原因是什么？

**Comment by dengwj25** [comment]
@houjin0803 大哥，最后是怎么解决的，我也遇到了一样的问题

**Comment by houjin0803** [comment]
我是参考这个链接进行修改的。
https://blog.csdn.net/weixin_40779727/article/details/109242629?spm=1001.2101.3001.6661.1&amp;utm_medium=distribute.pc_relevant_t0.none-task-blog-2%7Edefault%7ECTRLIST%7Edefault-1.no_search_link&amp;depth_1-utm_source=distribute.pc_relevant_t0.none-task-blog-2%7Edefault%7ECTRLIST%7Edefault-1.no_search_link
修改一下backend.py中的源码。不过我的是tf1.14还是会出现这个问题，我在服务器上用tf1.15没有出现这个报错，你也可以修改tf版本为1.15.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bojone/CLUE-bert4keras"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月26日(星期五) 晚上8:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bojone/CLUE-bert4keras] 关于keras training的出现：TypeError: __int__ returned non-int (type NoneType) (Issue #2)





 
@houjin0803 大哥，最后是怎么解决的，我也遇到了一样的问题
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dengwj25** [comment]
好的我试试，太感谢了。
################
测试后确实换成tf1.15就运行成功了。
