### ISSUE TITLE
苏神有考虑搞个GLUE的baseline么？

### ISSUE THREAD

**Issue by nishiwen1214** [bojone/CLUE-bert4keras#3]

**Comment by bojone** [comment]
暂时没有。主要是几乎没有做过英文任务（我也是个异类），所以怕是有很多坑～

**Comment by nishiwen1214** [comment]
> 暂时没有。主要是几乎没有做过英文任务（我也是个异类），所以怕是有很多坑～

我准备近期用bert4keras弄一个GLUE的baseline公开出来。感觉还是bert4keras的代码看着舒服～，其他的baseline看着头疼

**Comment by nishiwen1214** [comment]
英文GLUE的baseline已经弄好，https://github.com/nishiwen1214/GLUE-bert4keras
感谢苏神的bert4keras
